version: '3.3'

services:

  db:
    image: dockersamples/k8s-wordsmith-db

  words:
    image: dockersamples/k8s-wordsmith-api
    deploy:
      replicas: 5

  web:
    image: dockersamples/k8s-wordsmith-web
    ports:
     - "8080:80"
