version: '3.9'
# we'll keep the version for now to work in Compose and Swarm

services:
  db:
    image: postgres:10.0-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  api:
    build: api
    image: rajivnix/wordsmith-api
    deploy:
      replicas: 5

  web:
    build: web
    image: rajivnix/wordsmith-web
    ports:
     - "8080:80"